export const classes = [
  {
    startDate: "2023-02-13T09:00:00",
    endDate: "2023-02-13T10:30:00",
    title: "Math class",
    room: "Room 1",
  },
  {
    startDate: "2023-02-20T11:00:00",
    endDate: "2023-02-13T12:30:00",
    title: "History class",
    room: "Room 2",
  },
  {
    startDate: "2023-02-13T13:00:00",
    endDate: "2023-02-13T14:30:00",
    title: "Science class",
    room: "Room 3",
  },
  {
    startDate: "2023-02-14T09:00:00",
    endDate: "2023-02-14T10:30:00",
    title: "English class",
    room: "Room 1",
  },
  {
    startDate: "2023-02-21T11:00:00",
    endDate: "2023-02-14T12:30:00",
    title: "Art class",
    room: "Room 2",
  },
  {
    startDate: "2023-02-14T13:00:00",
    endDate: "2023-02-14T14:30:00",
    title: "Music class",
    room: "Room 3",
  },
];

export const options = [
  "sunny",
  "ocean",
  "ocean1",
  "ocean2",
  "ocean3",
  "ocean4",
  "ocean5",
  "ocean6",
  "ocean7",
  "ocean8",
  "ocean9",
  "bird",
  "cloud",
  "guitar",
  "apple",
  "banana",
  "desk",
  "chair",
  "computer",
  "table",
  "house",
  "car",
  "train",
  "tree",
  "dog",
  "cat",
  "book",
  "pen",
  "paper",
  "keyboard",
  "mouse",
  "television",
  "telephone",
  "music",
  "food",
  "water",
  "fire",
  "air",
  "sun",
  "moon",
  "star",
  "flower",
  "rain",
  "snow",
  "wind",
  "mountain",
  "oasis",
  "desert",
  "forest",
  "jungle",
  "river",
  "ocean",
  "beach",
  "island",
  "island",
  "port",
  "road",
  "highway",
  "street",
  "bridge",
  "tunnel",
  "park",
  "garden",
  "zoo",
  "school",
  "college",
  "university",
  "library",
  "museum",
  "hospital",
  "bank",
  "post office",
  "store",
  "supermarket",
  "cafe",
  "restaurant",
  "hotel",
  "airport",
  "train station",
  "bus station",
  "city",
  "town",
  "village",
  "country",
  "continent",
  "planet",
  "universe",
  "galaxy",
  "star system",
  "nebula",
  "black hole",
  "light",
  "sound",
  "color",
  "shape",
  "size",
  "number",
];
